// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import * as dotenvExpand from 'dotenv-expand';
import { env } from 'prisma/config';
import type { PrismaConfig } from 'prisma';

dotenvExpand.expand(dotenv.config());

export default {
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
} satisfies PrismaConfig;
